all:
	@echo "see /usr/src/linux/Documentation/locking"
	@echo "see /usr/src/linux/Documentation/locking/mutex-design.txt"
	@echo "see /usr/src/linux/Documentation/locking/spinlocks.txt"
	@echo
	@echo "see /usr/src/linux/Documentation/RCU/whatisRCU.txt"
